# -*- coding: utf-8 -*-
"""Gerenciador de Tabela de Símbolos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CLzLC0OXdbkk2Xo62V1g7K7nlSNKmEWz

# Criação da Tabela de Símbolos
"""

class TabelaDeSimbolos:
    def __init__(self):
        # Escopo global
        self.pilha_escopos = [{}]

    def entrar_escopo(self):
        """Cria um novo escopo."""
        self.pilha_escopos.append({})
        print("\n>>> Novo escopo criado.")

    def sair_escopo(self):
        """Remove o escopo atual."""
        if len(self.pilha_escopos) > 1:
            self.pilha_escopos.pop()
            print("\n>>> Escopo removido.")
        else:
            print("\n>>> Não é possível remover o escopo global.")

    def declarar(self, variavel, tipo):
        """Declara uma variável no escopo atual."""
        escopo_atual = self.pilha_escopos[-1]

        if variavel in escopo_atual:
            print(f"Erro: '{variavel}' já foi declarada neste escopo.")
        else:
            escopo_atual[variavel] = tipo
            print(f"Variável '{variavel}' declarada como '{tipo}'.")

    def buscar(self, variavel):
        """
        Procura a variável do escopo mais interno
        para o mais externo.
        """
        for escopo in reversed(self.pilha_escopos):
            if variavel in escopo:
                tipo = escopo[variavel]
                print(f"'{variavel}' encontrada com tipo '{tipo}'.")
                return tipo

        print(f"Erro: '{variavel}' não encontrada.")
        return None

    def mostrar_tabela(self):
        """Exibe todos os escopos."""
        print("\n===== TABELA DE SÍMBOLOS =====")

        for i, escopo in enumerate(self.pilha_escopos):
            print(f"Escopo {i}:")
            if escopo:
                for var, tipo in escopo.items():
                    print(f"  {var} -> {tipo}")
            else:
                print("  (vazio)")

        print("==============================")

"""# Exemplo de Uso"""

tabela = TabelaDeSimbolos()

# Escopo global
tabela.declarar("x", "int")
tabela.declarar("nome", "string")

tabela.buscar("x")

# Novo escopo
tabela.entrar_escopo()

tabela.declarar("y", "float")

tabela.buscar("y")
tabela.buscar("x")

tabela.mostrar_tabela()

# Sai do escopo
tabela.sair_escopo()

tabela.buscar("y")

tabela.mostrar_tabela()